### ISSUE TITLE
Need RESTResource.add(..) returning the id that added

### ISSUE THREAD

**Issue by wencheng** [lunatech-labs/play-module-resteasycrud#1]
Nice module!

If RESTResource.add(..) returns the id that added, it will be wonderful.

**Comment by FroMage** [comment]
What do you mean return? In theory it should add a Location HTTP header with the URL of the added entity, is that good for you?

**Comment by wencheng** [comment]
Yes! That's fine. All I want to know is the id of the record just added. Is that possible?

**Comment by FroMage** [comment]
Well, if the Location HTTP header is good for you then we'll add it in the next release. Are you comfortable with trying the new version of the module before it's released (from a git checkout)?

**Comment by wencheng** [comment]
Thank you very much.
I'll try it.

**Comment by FroMage** [comment]
Commit 9eee32ec61613682426482683a6328e4f4392e2f fixes this issue, can you give it a try?

**Comment by wencheng** [comment]
I tested.  Location header is fine to me. Thank you again.
