### ISSUE TITLE
Need an option for RESTResource.list(..) to returns plain array object

### ISSUE THREAD

**Issue by wencheng** [lunatech-labs/play-module-resteasycrud#2]
Hoping that RESTResource.list(..) may have an option to return a plain array object instead of DataTable.

Sample in xml:
    <books>
      <book>
        <title></title>
      </book>
      ...
    </books>

in JSON:
    {
      books: [
        {title: ''},
        {title: ''}
      ]
    }

**Comment by FroMage** [comment]
If you have a simple array how are you going to return the atom links and the paging information?
You can try overloading makeQueryResponse to return what you want or makeDataTable to make a DataTable that looks like you want. Is that good enough?

**Comment by wencheng** [comment]
um... You are right.
How about just replaces the &lt;rows> to &lt;book> and keeps the other part of DataTable? It'll be much easier to parse for the client that using the same parser for RESTResource.get(..).

I will try it.
Thank you very much!

**Comment by FroMage** [comment]
I'll have to think about this some more, since the list can be used by a generic client that doesn't know what the name/type of each element of the collection is, hence the generic name "rows".

Maybe something like that would work, though:

```
<rows>
 <book .../>
 <book .../>
</rows>
```
